'use client';
import Link from 'next/link';import {usePathname} from 'next/navigation';import {Icon,type IconName} from './icon';
import type {Role} from '@/lib/types';
const groups:{label:string;items:{href:string;label:string;icon:IconName;roles:Role[]}[]}[]=[
 {label:'01 — PILOTAGE',items:[{href:'/dashboard',label:'Command Center',icon:'dashboard',roles:['founder','admin']}]},
 {label:'02 — DÉVELOPPEMENT',items:[{href:'/growth',label:'Opportunity Radar',icon:'radar',roles:['founder','commercial','manager','quality','admin']},{href:'/offers',label:'Offer Workspace',icon:'briefcase',roles:['founder','commercial','manager','quality','admin']}]},
 {label:'03 — CAPITAL INTELLECTUEL',items:[{href:'/references',label:'Références',icon:'library',roles:['founder','commercial','manager','expert','quality','admin']},{href:'/experts',label:'Experts',icon:'users',roles:['founder','commercial','manager','expert','quality','admin']},{href:'/knowledge',label:'Knowledge',icon:'search',roles:['founder','commercial','manager','expert','quality','admin']}]},
 {label:'04 — DELIVERY',items:[{href:'/missions',label:'Missions',icon:'folder',roles:['founder','commercial','manager','expert','quality','admin']},{href:'/actions',label:'Actions',icon:'check',roles:['founder','commercial','manager','expert','quality','admin']}]},
 {label:'05 — GOUVERNANCE',items:[{href:'/billing',label:'Cash',icon:'cash',roles:['founder','admin']},{href:'/security',label:'Security',icon:'shield',roles:['founder','commercial','manager','expert','quality','admin']}]}];
export function PrimaryNav({role}:{role:Role}){const pathname=usePathname();return <nav className="nav" aria-label="Navigation principale">{groups.map(group=>{const items=group.items.filter(item=>item.roles.includes(role));if(!items.length)return null;return <div className="nav-group" key={group.label}><div className="nav-group-label">{group.label}</div>{items.map(item=>{const active=pathname===item.href||pathname.startsWith(`${item.href}/`);return <Link className={active?'active':''} aria-current={active?'page':undefined} href={item.href} key={item.href}><Icon className="nav-icon" name={item.icon}/>{item.label}</Link>})}</div>})}</nav>}
